apiVersion: v1
kind: Service
metadata:
  name: english-reader-service
spec:
  type: LoadBalancer  # Use NodePort or ClusterIP if LoadBalancer is not supported
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: english-reader
